<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="tflaptop-40-PC" name="com.twelvetwenty.suite.nace_reports.Service_Organization" tests="10" failures="0" timestamp="11 Jun 2015 18:11:10 GMT" time="1218.669" errors="2">
  <testcase name="test_Service_Organization" time="93.882" classname="com.twelvetwenty.suite.nace_reports.Service_Organization"/>
  <testcase name="test_Service_Organization" time="105.934" classname="com.twelvetwenty.suite.nace_reports.Service_Organization"/>
  <testcase name="test_Service_Organization" time="90.089" classname="com.twelvetwenty.suite.nace_reports.Service_Organization"/>
  <testcase name="test_Service_Organization" time="101.007" classname="com.twelvetwenty.suite.nace_reports.Service_Organization">
    <error type="java.lang.AssertionError" message="java.lang.AssertionError: Error while executing mT1_TH1_TCN_ReadXLSX keyword Fail ________ Error while executing mT1_TH1_TCN_ReadXLSX keyword nulljava.lang.AssertionError: Fail ________ Error while executing mT1_TH1_TCN_ReadXLSX keyword Fail ________ Error while executing mT1_TH1_TCN_ReadXLSX keyword null">
      <![CDATA[java.lang.AssertionError: java.lang.AssertionError: Error while executing mT1_TH1_TCN_ReadXLSX keyword Fail ________ Error while executing mT1_TH1_TCN_ReadXLSX keyword nulljava.lang.AssertionError: Fail ________ Error while executing mT1_TH1_TCN_ReadXLSX keyword Fail ________ Error while executing mT1_TH1_TCN_ReadXLSX keyword null
	at org.testng.Assert.fail(Assert.java:94)
	at com.twelvetwenty.base.CustomVerification.fail(CustomVerification.java:101)
	at com.twelvetwenty.base.CustomVerification.checkForVerificationErrors(CustomVerification.java:96)
	at com.twelvetwenty.suite.nace_reports.Service_Organization.test_Service_Organization(Service_Organization.java:198)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- test_Service_Organization -->
  <testcase name="test_Service_Organization" time="82.866" classname="com.twelvetwenty.suite.nace_reports.Service_Organization">
    <error type="java.lang.AssertionError" message="java.lang.AssertionError: expected [Bachelor&#039;s] but found [Total]java.lang.AssertionError: Error while executing mT1_TH1_TCN_ReadXLSX keyword nulljava.lang.AssertionError: Fail ________ Error while executing mT1_TH1_TCN_ReadXLSX keyword null">
      <![CDATA[java.lang.AssertionError: java.lang.AssertionError: expected [Bachelor's] but found [Total]java.lang.AssertionError: Error while executing mT1_TH1_TCN_ReadXLSX keyword nulljava.lang.AssertionError: Fail ________ Error while executing mT1_TH1_TCN_ReadXLSX keyword null
	at org.testng.Assert.fail(Assert.java:94)
	at com.twelvetwenty.base.CustomVerification.fail(CustomVerification.java:101)
	at com.twelvetwenty.base.CustomVerification.checkForVerificationErrors(CustomVerification.java:96)
	at com.twelvetwenty.suite.nace_reports.Service_Organization.test_Service_Organization(Service_Organization.java:198)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- test_Service_Organization -->
  <testcase name="test_Service_Organization" time="132.905" classname="com.twelvetwenty.suite.nace_reports.Service_Organization"/>
  <testcase name="test_Service_Organization" time="115.308" classname="com.twelvetwenty.suite.nace_reports.Service_Organization"/>
  <testcase name="test_Service_Organization" time="178.405" classname="com.twelvetwenty.suite.nace_reports.Service_Organization"/>
  <testcase name="test_Service_Organization" time="192.474" classname="com.twelvetwenty.suite.nace_reports.Service_Organization"/>
  <testcase name="test_Service_Organization" time="125.799" classname="com.twelvetwenty.suite.nace_reports.Service_Organization"/>
</testsuite> <!-- com.twelvetwenty.suite.nace_reports.Service_Organization -->
